spring:  
  jpa:  
    hibernate:  
      ddl-auto: none  
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${postgresqlUrl}
    username: ${postgresqlUser}
    password: ${postgresqlPwd}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      initial-size: 1
      maximum-pool-size: 10
      max-wait: 5000
      max-active: 10
      max-idle: 5
      min-idle: 1
      default-auto-commit: true
      data-source-properties: 
        preparedStatementCacheQueries: 0