version: "3.8"
services:
  postgresql:
    image: postgis/postgis:latest
    command: postgres -c 'max_connections=100'
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/structure.sql:/docker-entrypoint-initdb.d/structure.sql
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./postgres/create_indicadores_historico.sql:/docker-entrypoint-initdb.d/create_indicadores_historico.sql

